services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: edoo-nodejs
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    volumes:
      - ./database.sqlite:/app/database.sqlite
    networks:
      - benefits-network

networks:
  benefits-network:
    driver: bridge
