version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: edoo-nodejs
    ports:
      - "3000:3000"
    volumes:
      - sqlite_data:/app/data
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    restart: unless-stopped

volumes:
  sqlite_data:
    name: edoo_sqlite_data
